### ISSUE TITLE
Render only current step

### ISSUE THREAD

**Issue by carlosferrazza** [eanswer/TactileSimulation#1]
Is there a way to only render the current step of the environment, say after env.step(u) is called? Most of the examples in the repo seem to use the replay method, which is only called at the end of an episode. Thanks!

**Comment by eanswer** [comment]
Unfortunately it only supports replay mode for now. But it should be possible to add the step-wise rendering feature in the C++ visualizer. This is mainly because currently the renderer and the simulation share the same thread, so the simulation will get blocked if rendering window is open.
