### ISSUE TITLE
About the feed-forward term

### ISSUE THREAD

**Issue by chenwh14** [eanswer/TactileSimulation#2]
Hello authors, I find that in TactileInsertion environment, a feed-forward term is added to u[2], which corresponds to the commanded gripper height as I think. In other scripts, I also notice that this feed-forward term is hard-coded. Could you please explain why there is a feed-forward term and its physical meanings? Thanks!

**Comment by eanswer** [comment]
This term is used to compensate the tracking error introduced by the gravity of the robot. Without a feed-forward term, the PD controller will have consistent tracking errors.
